name: graph_plus_exporter_web
version: 1.0.0-alpha
description: >-
  A graph_plus_exporter plugin for the 'web' platform

  This package provides a web implementation for the graph_plus_exporter package
repository: https://github.com/ArchMindCo/flutter-graph-plus-exporter-web
topics:
  - utils
  - plugin
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: GraphViewExporterPlugin
        fileName: graph_view_exporter_web.dart